### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by JohnGFa** [Artelnics/opennn#188]
I have downloaded the project but it seems incomplete. It's missing the files "principal_components_layer.cpp" and "principal_components_layer.h".

However, even after downloading these from an alternate source the make fails with errors starting:

"../eigen/unsupported/Eigen/CXX11/src/Tensor/TensorExpr.h:150:52: error: ‘const double’ is not a class, struct, or union type
                typename RhsXprType::Scalar)>::type Scalar;"

Happy to provide more details if needed!

**Comment by BitMeahy** [comment]
Hi there,

I have encountered this problem, too.

Some help would be highly appreciated!

Thanks and ciao,

Nils

**Comment by BitMeahy** [comment]
Hi,

I use this release for now:
https://github.com/Artelnics/opennn/releases/tag/v5.0.5

It seems to work.

Thx and ciao!

**Comment by ViktorHoffmann** [comment]
I have also managed to make it work using v5.0.5.

Though it seems to me that there is also a linker issue as i often got: _"cannot find -lopennn"_.

After working around that problem too when i try to run an example i get errors like:
_"OpenNN. Iris Plant Example.
OpenNN Exception: DataSet class.
void read_csv() method.
Cannot open data file: ../data/iris_plant_original.csv"_
even though the file is very much present and accessible.

These may all be seperate issues but they all appeared with the same version somehow.

**Comment by BitMeahy** [comment]
Hi Viktor,

> _"OpenNN. Iris Plant Example. OpenNN Exception: DataSet class. void read_csv() method. Cannot open data file: ../data/iris_plant_original.csv"_
> even though the file is very much present and accessible.

1. Create a directory named "Release" in your "examples/iris_plant/" folder.
2. Copy the executable "iris_plant" into this "Release" folder.
3. Start ./iris_plant inside this "Release" folder.

This worked for me.

Good luck and all the best!

**Comment by xloem** [comment]
I have made these commits to temporarily resolve this:
a7cf4eb6fde29b37acfd1397e2bff05a873a319c brings back references to principal components
90b75ec60fd252cff4e0834857dafdd8abd46860 brings back principal components files
5e53996a431e8258703968d0898422c549729cb0 brings back pima indians example, also missing

I chose to bring back the files rather than remove their cmake entries because there is no explanation why they are missing, and i wanted to continue worrying about it.
Commits can be applied via `git cherry-pick [commit]` where `[commit]` is the hash.

**Comment by adventurist** [comment]
> I have made these commits in a fork to temporarily resolve this: [a7cf4eb](https://github.com/Artelnics/opennn/commit/a7cf4eb6fde29b37acfd1397e2bff05a873a319c) brings back references to principal components [90b75ec](https://github.com/Artelnics/opennn/commit/90b75ec60fd252cff4e0834857dafdd8abd46860) brings back principal components files [5e53996](https://github.com/Artelnics/opennn/commit/5e53996a431e8258703968d0898422c549729cb0) brings back pima indians example, also missing
> 
> I chose to bring back the files rather than remove their cmake entries because there is no explanation why they are missing, and i wanted to continue worrying about it. Commits can be applied via `git cherry-pick [commit]` where `[commit]` is the hash.
> 
> The dev branch is building for me today if current pull requests and above commits are added.

This procedure didn't work for me today

**Comment by xloem** [comment]
It does seem like more dev work has happened since then.  I'm not set up with this library any more, sorry.  @davidge807 you have recent commits to the repo; do you know if these build issues and changes are known/resolved?

**Comment by adventurist** [comment]
I just built an older commit, based just after the release mentioned above: 
`93ad9d921f77d2bfaedd852fd0a8a80e14dac890`

Tests broken, but still something I can dabble with :)

**Comment by davidge807** [comment]
Hi @xloem @adventurist 

We've just updated cMakeLists (removed some old files and added missing ones) in the dev branch.

Do these building issues continue occurring to you?
